title: Cooking Compass
description:
google_analytics:
show_downloads: true
remote_theme: "jekyll/minima@1e8a445"

navigation:
  - name: "Home"
    link: "/"
  - name: "Cooking Compass"
    link: "/cooking-compass"

gems:
  - jekyll-mentions
  
